<?php

declare(strict_types=1);

class Translator
{
    public const DEFAULT_LANGUAGE = 'es';

    private static array $TEXTOS = [
        'es' => [
            'appSubtitulo' => 'Sistema de Gestión de Recursos y Soporte Informático',
            'footer' => '© SGRSI – Proyecto Bachillerato Tecnológico',
            'navInicio' => 'Inicio',
            'navInventario' => 'Inventario',
            'navUsuarios' => 'Usuarios',
            'navPrestamos' => 'Préstamos',
            'navTickets' => 'Tickets',
            'navReportes' => 'Reportes',
            'navHistorial' => 'Historial',
            'navCerrarSesion' => 'Cerrar sesión',
            'tituloInicio' => 'SGRSI – Inicio',
            'bienvenidaTitulo' => 'Bienvenido a SGRSI',
            'bienvenidaTexto' => 'Gestioná equipos, usuarios, préstamos y tickets de soporte desde un solo lugar. Usá el menú de arriba o accedé directamente a cada módulo.',
            'moduloInventarioDesc' => 'Registrá y consultá los equipos disponibles.',
            'moduloUsuariosDesc' => 'Alta de solicitantes, técnicos y administradores.',
            'moduloPrestamosDesc' => 'Registrá préstamos y devoluciones de equipos.',
            'moduloTicketsDesc' => 'Mesa de ayuda: abrí y cerrá tickets de soporte.',
            'moduloReportesDesc' => 'Resumen del estado del sistema en tiempo real.',
            'moduloHistorialDesc' => 'Revisá el registro de tickets y reportes anteriores.',
            'tituloInventario' => 'SGRSI – Inventario',
            'registroEquiposTitulo' => 'Registro de Equipos',
            'labelModelo' => 'Modelo',
            'labelMarca' => 'Marca',
            'labelNumeroSerie' => 'Número de serie',
            'labelTipoEquipo' => 'Tipo de equipo',
            'opcionSeleccionar' => 'Seleccionar…',
            'placeholderModelo' => 'Ej: ProDesk 400',
            'placeholderMarca' => 'Ej: HP',
            'placeholderNumeroSerie' => 'Ej: SN-2024-0001',
            'botonAgregarEquipo' => 'Agregar Equipo',
            'avisoSoloConsultaInventario' => 'Tu rol permite consultar el inventario, pero no registrar equipos nuevos.',
            'msgEquipoAgregado' => 'Equipo agregado: ',
            'thNum' => '#',
            'thModelo' => 'Modelo',
            'thMarca' => 'Marca',
            'thNSerie' => 'N° Serie',
            'thTipo' => 'Tipo',
            'thEstado' => 'Estado',
            'tituloUsuarios' => 'SGRSI – Usuarios',
            'altaUsuariosTitulo' => 'Alta de Usuarios',
            'labelCedula' => 'Cédula de identidad',
            'labelNombreCompleto' => 'Nombre completo',
            'labelCorreo' => 'Correo electrónico',
            'labelRol' => 'Rol',
            'opcionSeleccionarRol' => 'Seleccionar rol…',
            'placeholderCedula' => 'Ej: 3.814.725-8 o 38147258',
            'placeholderNombre' => 'Ej: María González',
            'placeholderCorreo' => 'usuario@institucion.edu',
            'botonAgregarUsuario' => 'Agregar Usuario',
            'msgCedulaInvalida' => 'La cédula no es válida (revisá el dígito verificador)',
            'msgUsuarioAgregado' => 'Usuario agregado: ',
            'msgUsuarioEliminado' => 'Usuario eliminado',
            'thCedula' => 'Cédula',
            'thNombre' => 'Nombre',
            'thCorreo' => 'Correo',
            'thRol' => 'Rol',
            'thAccionCol' => 'Acción',
            'botonEliminar' => 'Eliminar',
            'confirmEliminarUsuario' => '¿Eliminar este usuario?',
            'tituloPrestamos' => 'SGRSI – Préstamos',
            'registroPrestamosTitulo' => 'Registro de Préstamos',
            'labelSolicitante' => 'Solicitante',
            'labelEquipo' => 'Equipo',
            'labelFechaDevolucion' => 'Fecha estimada de devolución',
            'labelObservacion' => 'Observación',
            'opcionSeleccionarSolicitante' => 'Seleccionar solicitante…',
            'opcionSeleccionarEquipo' => 'Seleccionar equipo…',
            'placeholderObservacion' => 'Ej: Para trabajo en clase',
            'botonRegistrarPrestamo' => 'Registrar Préstamo',
            'msgPrestamoRegistrado' => 'Préstamo registrado',
            'msgEquipoDevuelto' => 'Equipo devuelto',
            'thSolicitante' => 'Solicitante',
            'thEquipo' => 'Equipo',
            'thDevolucion' => 'Devolución',
            'botonDevolver' => 'Devolver',
            'tituloTickets' => 'SGRSI – Tickets',
            'mesaAyudaTitulo' => 'Mesa de Ayuda – Tickets',
            'labelTitulo' => 'Título',
            'labelPrioridad' => 'Prioridad',
            'labelDescripcionProblema' => 'Descripción del problema',
            'placeholderTitulo' => 'Ej: PC no enciende',
            'placeholderDescripcion' => 'Describí el problema con detalle…',
            'botonCrearTicket' => 'Crear Ticket',
            'msgTicketCreado' => 'Ticket creado correctamente',
            'msgTicketCerrado' => 'Ticket cerrado',
            'thFecha' => 'Fecha',
            'thTitulo' => 'Título',
            'thPrioridad' => 'Prioridad',
            'thProblema' => 'Problema',
            'botonCerrar' => 'Cerrar',
            'tituloReportes' => 'SGRSI – Reportes',
            'reportesTitulo' => 'Reportes del Sistema',
            'reportesDesc' => 'Resumen del estado actual del inventario, préstamos y tickets.',
            'statEquiposTotales' => 'Equipos totales',
            'statDisponibles' => 'Disponibles',
            'statPrestados' => 'Prestados',
            'statTicketsAbiertos' => 'Tickets abiertos',
            'statTicketsCerrados' => 'Tickets cerrados',
            'statPrestamosActivos' => 'Préstamos activos',
            'thConcepto' => 'Concepto',
            'thValor' => 'Valor',
            'filaTotalEquipos' => 'Total de equipos',
            'filaEquiposDisponibles' => 'Equipos disponibles',
            'filaEquiposPrestados' => 'Equipos prestados',
            'filaTicketsAbiertos' => 'Tickets abiertos',
            'filaTicketsCerrados' => 'Tickets cerrados',
            'filaPrestamosActivos' => 'Préstamos activos',
            'filaPrestamosDevueltos' => 'Préstamos devueltos',
            'reporteGenerado' => 'Reporte generado el ',
            'tituloHistorial' => 'SGRSI – Historial',
            'historialTitulo' => 'Historial',
            'thDescripcion' => 'Descripción',
            'thTicket' => 'Ticket',
            'thServicio' => 'Servicio',
        ],
        'en' => [
            'appSubtitulo' => 'Resource and IT Support Management System',
            'footer' => '© SGRSI – Technical High School Project',
            'navInicio' => 'Home',
            'navInventario' => 'Inventory',
            'navUsuarios' => 'Users',
            'navPrestamos' => 'Loans',
            'navTickets' => 'Tickets',
            'navReportes' => 'Reports',
            'navHistorial' => 'History',
            'navCerrarSesion' => 'Log out',
            'tituloInicio' => 'SGRSI – Home',
            'bienvenidaTitulo' => 'Welcome to SGRSI',
            'bienvenidaTexto' => 'Manage equipment, users, loans and support tickets from one place. Use the menu above or go straight to each module.',
            'moduloInventarioDesc' => 'Register and check available equipment.',
            'moduloUsuariosDesc' => 'Add requesters, technicians and administrators.',
            'moduloPrestamosDesc' => 'Register equipment loans and returns.',
            'moduloTicketsDesc' => 'Help desk: open and close support tickets.',
            'moduloReportesDesc' => 'Real-time summary of the system status.',
            'moduloHistorialDesc' => 'Review the log of past tickets and reports.',
            'tituloInventario' => 'SGRSI – Inventory',
            'registroEquiposTitulo' => 'Equipment Registration',
            'labelModelo' => 'Model',
            'labelMarca' => 'Brand',
            'labelNumeroSerie' => 'Serial number',
            'labelTipoEquipo' => 'Equipment type',
            'opcionSeleccionar' => 'Select…',
            'placeholderModelo' => 'E.g.: ProDesk 400',
            'placeholderMarca' => 'E.g.: HP',
            'placeholderNumeroSerie' => 'E.g.: SN-2024-0001',
            'botonAgregarEquipo' => 'Add Equipment',
            'avisoSoloConsultaInventario' => 'Your role allows you to view the inventory, but not to register new equipment.',
            'msgEquipoAgregado' => 'Equipment added: ',
            'thNum' => '#',
            'thModelo' => 'Model',
            'thMarca' => 'Brand',
            'thNSerie' => 'Serial No.',
            'thTipo' => 'Type',
            'thEstado' => 'Status',
            'tituloUsuarios' => 'SGRSI – Users',
            'altaUsuariosTitulo' => 'User Registration',
            'labelCedula' => 'ID number',
            'labelNombreCompleto' => 'Full name',
            'labelCorreo' => 'Email address',
            'labelRol' => 'Role',
            'opcionSeleccionarRol' => 'Select role…',
            'placeholderCedula' => 'E.g.: 3.814.725-8 or 38147258',
            'placeholderNombre' => 'E.g.: Jane Smith',
            'placeholderCorreo' => 'user@institution.edu',
            'botonAgregarUsuario' => 'Add User',
            'msgCedulaInvalida' => 'The ID number is not valid (check the verification digit)',
            'msgUsuarioAgregado' => 'User added: ',
            'msgUsuarioEliminado' => 'User deleted',
            'thCedula' => 'ID',
            'thNombre' => 'Name',
            'thCorreo' => 'Email',
            'thRol' => 'Role',
            'thAccionCol' => 'Action',
            'botonEliminar' => 'Delete',
            'confirmEliminarUsuario' => 'Delete this user?',
            'tituloPrestamos' => 'SGRSI – Loans',
            'registroPrestamosTitulo' => 'Loan Registration',
            'labelSolicitante' => 'Requester',
            'labelEquipo' => 'Equipment',
            'labelFechaDevolucion' => 'Estimated return date',
            'labelObservacion' => 'Note',
            'opcionSeleccionarSolicitante' => 'Select requester…',
            'opcionSeleccionarEquipo' => 'Select equipment…',
            'placeholderObservacion' => 'E.g.: For classroom use',
            'botonRegistrarPrestamo' => 'Register Loan',
            'msgPrestamoRegistrado' => 'Loan registered',
            'msgEquipoDevuelto' => 'Equipment returned',
            'thSolicitante' => 'Requester',
            'thEquipo' => 'Equipment',
            'thDevolucion' => 'Return',
            'botonDevolver' => 'Return',
            'tituloTickets' => 'SGRSI – Tickets',
            'mesaAyudaTitulo' => 'Help Desk – Tickets',
            'labelTitulo' => 'Title',
            'labelPrioridad' => 'Priority',
            'labelDescripcionProblema' => 'Problem description',
            'placeholderTitulo' => 'E.g.: PC won\'t turn on',
            'placeholderDescripcion' => 'Describe the problem in detail…',
            'botonCrearTicket' => 'Create Ticket',
            'msgTicketCreado' => 'Ticket created successfully',
            'msgTicketCerrado' => 'Ticket closed',
            'thFecha' => 'Date',
            'thTitulo' => 'Title',
            'thPrioridad' => 'Priority',
            'thProblema' => 'Problem',
            'botonCerrar' => 'Close',
            'tituloReportes' => 'SGRSI – Reports',
            'reportesTitulo' => 'System Reports',
            'reportesDesc' => 'Summary of the current status of inventory, loans and tickets.',
            'statEquiposTotales' => 'Total equipment',
            'statDisponibles' => 'Available',
            'statPrestados' => 'Loaned',
            'statTicketsAbiertos' => 'Open tickets',
            'statTicketsCerrados' => 'Closed tickets',
            'statPrestamosActivos' => 'Active loans',
            'thConcepto' => 'Item',
            'thValor' => 'Value',
            'filaTotalEquipos' => 'Total equipment',
            'filaEquiposDisponibles' => 'Available equipment',
            'filaEquiposPrestados' => 'Loaned equipment',
            'filaTicketsAbiertos' => 'Open tickets',
            'filaTicketsCerrados' => 'Closed tickets',
            'filaPrestamosActivos' => 'Active loans',
            'filaPrestamosDevueltos' => 'Returned loans',
            'reporteGenerado' => 'Report generated on ',
            'tituloHistorial' => 'SGRSI – History',
            'historialTitulo' => 'History',
            'thDescripcion' => 'Description',
            'thTicket' => 'Ticket',
            'thServicio' => 'Service',
        ],
    ];

    private static array $VALORES = [
        'es' => [
            'Disponible' => 'Disponible',
            'Prestado' => 'Prestado',
            'En reparacion' => 'En reparación',
            'Dado de baja' => 'Dado de baja',
            'PC' => 'PC',
            'Laptop' => 'Laptop',
            'Monitor' => 'Monitor',
            'Proyector' => 'Proyector',
            'Television' => 'Televisión',
            'Otro' => 'Otro',
            'Entregado' => 'Entregado',
            'Devuelto' => 'Devuelto',
            'Rechazado' => 'Rechazado',
            'Abierto' => 'Abierto',
            'Cerrado' => 'Cerrado',
            'Alta' => 'Alta',
            'Media' => 'Media',
            'Baja' => 'Baja',
            'Administrador' => 'Administrador',
            'Tecnico' => 'Técnico',
            'Solicitante' => 'Solicitante',
        ],
        'en' => [
            'Disponible' => 'Available',
            'Prestado' => 'Loaned',
            'En reparacion' => 'Under repair',
            'Dado de baja' => 'Decommissioned',
            'PC' => 'PC',
            'Laptop' => 'Laptop',
            'Monitor' => 'Monitor',
            'Proyector' => 'Projector',
            'Television' => 'TV',
            'Otro' => 'Other',
            'Entregado' => 'Delivered',
            'Devuelto' => 'Returned',
            'Rechazado' => 'Rejected',
            'Abierto' => 'Open',
            'Cerrado' => 'Closed',
            'Alta' => 'High',
            'Media' => 'Medium',
            'Baja' => 'Low',
            'Administrador' => 'Administrator',
            'Tecnico' => 'Technician',
            'Solicitante' => 'Requester',
        ],
    ];

    public static function currentLanguage(): string
    {
        if (isset($_GET['idioma']) && in_array($_GET['idioma'], ['es', 'en'], true)) {
            $language = $_GET['idioma'];
            setcookie('idioma', $language, time() + 60 * 60 * 24 * 365, '/');
            return $language;
        }

        if (isset($_COOKIE['idioma']) && in_array($_COOKIE['idioma'], ['es', 'en'], true)) {
            return $_COOKIE['idioma'];
        }

        return self::DEFAULT_LANGUAGE;
    }

    public static function translate(string $key): string
    {
        $language = self::currentLanguage();
        return self::$TEXTOS[$language][$key] ?? $key;
    }

    public static function value(string $value): string
    {
        $language = self::currentLanguage();
        return self::$VALORES[$language][$value] ?? $value;
    }
}

function t(string $key): string
{
    return Translator::translate($key);
}

function tv(string $value): string
{
    return Translator::value($value);
}
